
platform :ios, '9.0'

target 'TWJ' do
pod 'Masonry', '~>1.1.0'
pod 'AFNetworking','~>3.1.0'
pod 'IQKeyboardManager', '~> 5.0.4'
pod 'SVProgressHUD', '~> 1.1.3'
pod “FMDB"
pod 'SDWebImage', '~> 3.7.6'
end

